# Copyright (c) 2014-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

include_defs('//CSSLAYOUT_DEFS')

COMPILER_FLAGS = [
  '-std=c++11',
  '-Wno-missing-prototypes',
]

cxx_library(
  name = 'gtest',
  srcs = glob([gtest_folder + '/src/*.cc']),
  exported_headers = subdir_glob([
    (gtest_folder + '/include', '**/*.h'),
    (gtest_folder, 'src/*.h'),
    (gtest_folder, 'src/*.cc'),
  ]),
  header_namespace = '',
  compiler_flags = COMPILER_FLAGS,
  deps = [],
  visibility = [CSSLAYOUT_ROOT],
)
